<?php
namespace Ce\Sdk\Rpc\Base;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface RpcServiceIf
{
    /**
     * @param string $classname
     * @param string $method
     * @param string $arglist
     * @param string $extra
     * @return \Ce\Sdk\Rpc\Base\ResponseData
     * @throws \Ce\Sdk\Rpc\Base\InvalidException
     */
    public function callRpc($classname, $method, $arglist, $extra);
}
