<?php
namespace Ce\Sdk\Rpc\Base;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class RpcService_callRpc_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'classname',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'method',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'arglist',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'extra',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $classname = null;
    /**
     * @var string
     */
    public $method = null;
    /**
     * @var string
     */
    public $arglist = null;
    /**
     * @var string
     */
    public $extra = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['classname'])) {
                $this->classname = $vals['classname'];
            }
            if (isset($vals['method'])) {
                $this->method = $vals['method'];
            }
            if (isset($vals['arglist'])) {
                $this->arglist = $vals['arglist'];
            }
            if (isset($vals['extra'])) {
                $this->extra = $vals['extra'];
            }
        }
    }

    public function getName()
    {
        return 'RpcService_callRpc_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->classname);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->method);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->arglist);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->extra);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('RpcService_callRpc_args');
        if ($this->classname !== null) {
            $xfer += $output->writeFieldBegin('classname', TType::STRING, 1);
            $xfer += $output->writeString($this->classname);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->method !== null) {
            $xfer += $output->writeFieldBegin('method', TType::STRING, 2);
            $xfer += $output->writeString($this->method);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->arglist !== null) {
            $xfer += $output->writeFieldBegin('arglist', TType::STRING, 3);
            $xfer += $output->writeString($this->arglist);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->extra !== null) {
            $xfer += $output->writeFieldBegin('extra', TType::STRING, 4);
            $xfer += $output->writeString($this->extra);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
